@startuml

title __DIAGRAME's Class Diagram__\n

  namespace  {
    class Animal {
        - name : String
        - nameMaster : String
        - race : String
        - specie : Espece
        - suiviAnimal : SuiviAnimal
        + Animal()
        + Animal()
        + getAnimalObj()
        + getEspeseInfo()
        + getEspeseObj()
        + getName()
        + getNameMaster()
        + getRace()
        + getSuivi()
        + printAnimal()
        + setEspeseObj()
        + setName()
        + setNameMaster()
        + setRace()
        + setSuivi()
        + test()
    }
  }
  

  namespace  {
    class CabinnetVeterinaireImpl {
        - patients : List<IAnimal>
        - runningClients : List<IDistributedClient>
        + CabinnetVeterinaireImpl()
        + CabinnetVeterinaireImpl()
        + addPatient()
        + bindClientToCabinet()
        + deletePatient()
        + getCurrentPatientNumber()
        + searchAllAnimal()
        + searchAllAnimal()
        + sendAlert()
        + unbindClientToCabinet()
        - searchAllAnimalOfName()
        - searchAnimalByFullName()
    }
  }
  

  namespace  {
    class Client {
        + Client()
        + checkAlert()
        {static} + main()
    }
  }
  

  namespace  {
    class Espece {
        - lifeExpectancy : int
        - name : String
        {static} - serialVersionUID : long
        + Espece()
        + Espece()
        + getlifeExpectancy()
        + getname()
        + setlifeExpectancy()
        + setname()
    }
  }
  

  namespace  {
    interface IAnimal {
        {abstract} + getAnimalObj()
        {abstract} + getEspeseInfo()
        {abstract} + getEspeseObj()
        {abstract} + getName()
        {abstract} + getNameMaster()
        {abstract} + getRace()
        {abstract} + getSuivi()
        {abstract} + printAnimal()
        {abstract} + setEspeseObj()
        {abstract} + setName()
        {abstract} + setNameMaster()
        {abstract} + setRace()
        {abstract} + setSuivi()
        {abstract} + test()
    }
  }
  

  namespace  {
    interface ICabinetVeterinaire {
        {abstract} + addPatient()
        {abstract} + bindClientToCabinet()
        {abstract} + deletePatient()
        {abstract} + getCurrentPatientNumber()
        {abstract} + searchAllAnimal()
        {abstract} + searchAllAnimal()
        {abstract} + sendAlert()
        {abstract} + unbindClientToCabinet()
    }
  }
  

  namespace  {
    interface IDistributedClient {
        {abstract} + checkAlert()
    }
  }
  

  namespace  {
    interface IEspece {
        {abstract} + getlifeExpectancy()
        {abstract} + getname()
        {abstract} + setlifeExpectancy()
        {abstract} + setname()
    }
  }
  

  namespace  {
    interface ISuiviAnimal {
        {abstract} + getSuivi()
        {abstract} + setSuivi()
    }
  }
  

  namespace  {
    class Server {
        + Server()
        {static} + main()
    }
  }
  

  namespace  {
    class SuiviAnimal {
        - suivi : String
        + SuiviAnimal()
        + SuiviAnimal()
        + getSuivi()
        + setSuivi()
    }
  }
  

  Animal .up.|> IAnimal
  CabinnetVeterinaireImpl .up.|> ICabinetVeterinaire
  Client .up.|> IDistributedClient
  Espece .up.|> IEspece
  SuiviAnimal .up.|> ISuiviAnimal


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
